<a href="https://colab.research.google.com/github/Souvik2215151029/HW-01_id-29/blob/main/HW_02_id_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

# With Seed
np.random.seed(10)  # Setting seed to 10
seeded_matrix = np.random.randint(1, 51, (3, 3))
print("Seeded Random Matrix:\n", seeded_matrix)

# Without Seed
np.random.seed(None)  # No seed, generates different values each time
non_seeded_matrix = np.random.randint(1, 51, (3, 3))
print("\nNon-Seeded Random Matrix:\n", non_seeded_matrix)

Seeded Random Matrix:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Non-Seeded Random Matrix:
 [[43  5 41]
 [18 21 14]
 [39 49 21]]
